/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 07:27:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.finance;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class finance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>用户分页列表</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("\ttable th{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t#checkChange input{\r\n");
      out.write("\t\tborder:0px;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("  <body>\r\n");
      out.write("  \t<div align=\"center\"><h3>门店订单统计</h3></div>\r\n");
      out.write("\t   <table id=\"tt\" class=\"easyui-datagrid\"   style=\"width:100%;height:50%;\"\r\n");
      out.write("\t\t\tpagination=\"true\" fitColumns=\"true\" rownumbers=\"true\" toolbar=\"#tb\" iconCls=\"icon-more\" data-options=\"singleSelect:true,collapsible:true,\r\n");
      out.write("\t\t\turl:'finance/page.do',method:'post'\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'billtype',width:100,align:'center'\" sortable=\"true\">账单类型</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'spendtype',width:80,align:'center'\" formatter='formatState1'>支出类型</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'remark',width:80,align:'center',sortable:true\">支出备注</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'addtime',width:80,align:'center'\">账单时间</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'money',width:80,align:'center',sortable:true\">支出金额</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"tb\" style=\"padding:3px\">\r\n");
      out.write("\t\t<select id=\"cc\" class=\"easyui-combobox\" name=\"billtype\"  style=\"width:200px;\">   \r\n");
      out.write("\t\t    <option value=\"\">请选择账单类型</option>   \r\n");
      out.write("\t\t    <option>异常金额</option>   \r\n");
      out.write("\t\t    <option>维修金额</option>   \r\n");
      out.write("\t\t    <option>订单金额</option>\r\n");
      out.write("\t\t</select> \r\n");
      out.write("\t\t<select id=\"dd\" class=\"easyui-combobox\" name=\"spendtype\"  style=\"width:200px;\">   \r\n");
      out.write("\t\t    <option value=\"\">请选择支出类型</option>   \r\n");
      out.write("\t\t    <option value=\"1\">支出</option>   \r\n");
      out.write("\t\t    <option value=\"2\">收入</option>     \r\n");
      out.write("\t\t</select> \r\n");
      out.write("\t\t\t<input name=\"begintime\" id=\"d1\" type=\"text\" data-options=\"formatter:formatter,parser:parser\"    class=\"easyui-datebox\" >到\r\n");
      out.write("\t\t\t<input name=\"endtime\" id=\"d2\" type=\"text\" data-options=\"formatter:formatter,parser:parser\"   class=\"easyui-datebox\" >\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" plain=\"true\" onclick=\"doSearch()\">查询</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px;height:280px;padding:10px 20px\"\r\n");
      out.write("\t\tclosed=\"true\"  buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div align=\"center\"><h3>收支总计</h3></div>\r\n");
      out.write("\t\t<table id=\"tt\" class=\"easyui-datagrid\"   style=\"width:100%;height:50%;\"\r\n");
      out.write("\t\t\tpagination=\"true\" fitColumns=\"true\" rownumbers=\"true\"  iconCls=\"icon-more\" data-options=\"singleSelect:true,collapsible:true,\r\n");
      out.write("\t\t\turl:'finance/list.do',method:'post'\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'zzc',width:100,align:'center'\" sortable=\"true\">支出总金额</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'zsr',width:80,align:'center'\" >收入总金额</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'zwx',width:80,align:'center',sortable:true\">维修总金额</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'zdd',width:80,align:'center'\">订单总金额</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'zyc',width:80,align:'center',sortable:true\">异常总金额</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t//添加序号\r\n");
      out.write("\t\t $(function () {\r\n");
      out.write("            $('#tt').closest('div.datagrid-view').find('div.datagrid-header-rownumber').html(' 序号 ');\r\n");
      out.write("        \t}) \r\n");
      out.write("\t\t//查询方法\r\n");
      out.write("\t\t  function doSearch(){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tbilltype: $('#cc').val(),\r\n");
      out.write("\t\t\t\t\tspendtype: $('#dd').val(),\r\n");
      out.write("\t\t\t\t\tbegintime: $('#d1').val(),\r\n");
      out.write("\t\t\t\t\tendtime: $('#d2').val()\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t//给单数字状态换成汉字状态1代表支出2代表收入\r\n");
      out.write("\t\tfunction formatState1(value,row,index){//val 当前列的值  row取当前行的值\r\n");
      out.write("\t    \tif (row.spendtype==2){\r\n");
      out.write("\t    \t\treturn '收入';\r\n");
      out.write("\t    \t} else if (row.spendtype==1){\r\n");
      out.write("\t    \t\treturn '支出';\r\n");
      out.write("\t    \t}   \r\n");
      out.write("  \t \t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t //修改日历框的显示格式 \r\n");
      out.write("  function formatter(date){  \r\n");
      out.write("        var y = date.getFullYear();  \r\n");
      out.write("        var m = date.getMonth()+1;  \r\n");
      out.write("        var d = date.getDate();  \r\n");
      out.write("        var h = date.getHours();  \r\n");
      out.write("        var str = y+'-'+(m<10?('0'+m):m)+'-'+(d<10?('0'+d):d);  \r\n");
      out.write("        return str;  \r\n");
      out.write("    }  \r\n");
      out.write("    function parser(s){  \r\n");
      out.write("        if (!s) return new Date();  \r\n");
      out.write("        var y = s.substring(0,4);  \r\n");
      out.write("        var m =s.substring(5,7);  \r\n");
      out.write("        var d = s.substring(8,10);  \r\n");
      out.write("        var h = s.substring(11,14);  \r\n");
      out.write("        var min = s.substring(15,17);  \r\n");
      out.write("        var sec = s.substring(18,20);  \r\n");
      out.write("        if (!isNaN(y) && !isNaN(m) && !isNaN(d)){  \r\n");
      out.write("            return new Date(y,m-1,d);  \r\n");
      out.write("        } else {  \r\n");
      out.write("            return new Date();  \r\n");
      out.write("        }  \r\n");
      out.write("    }  \r\n");
      out.write("\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
