/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 07:21:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backStage.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class forWordOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>前台订单</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//给单数字状态换成汉字状态\r\n");
      out.write("\t\tfunction formatState(value,row,index){//val 当前列的值  row取当前行的值\r\n");
      out.write("\t    \tif (row.goods_status==1){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">待审核</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==2){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">审核通过</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==3){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">入库</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==4){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">装配</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==5){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">出库</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==6){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">目的地站</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==6){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">已签收</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==66){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">退单</span>';\r\n");
      out.write("\t    \t} \r\n");
      out.write("  \t \t } \r\n");
      out.write("  \t \t \r\n");
      out.write("  \t \t //弹出更新方法\r\n");
      out.write("\t\tfunction overStoreOrder(){\r\n");
      out.write("\t\t\tvar row = $('#tt').datagrid('getSelected');\r\n");
      out.write("\t\t   //获取选中行\r\n");
      out.write("\t\t\tif (row){\r\n");
      out.write("\t\t\t  \t//alert(row.id);\r\n");
      out.write("\t\t\t     //弹出框\r\n");
      out.write("\t\t\t\t$('#dlg').dialog('open').dialog('setTitle','添加目的地门店');\r\n");
      out.write("\t\t\t\t//加载数据 根据datagrid里面的field的名称和form表单的名称必须一致\r\n");
      out.write("\t\t\t\t$('#fm').form('load',row);\r\n");
      out.write("\t\t\t\turl = 'order/update.do?id='+row.id;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t     $.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\tmsg: '请至少选中一行！！！'//提示信息\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//保存操作(添加和保存使用的一个方法)\r\n");
      out.write("\t\tfunction saveUser(){\r\n");
      out.write("\t\t\t$('#fm').form('submit',{//给form表单绑定submit事件\r\n");
      out.write("\t\t\t\turl: url,//请求的url地址\r\n");
      out.write("\t\t\t\tonSubmit: function(){//对form表单校验\r\n");
      out.write("\t\t\t\t\treturn $(this).form('validate');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(result){//数据保存后的回调函数\r\n");
      out.write("\t\t\t\t\tvar result = eval('('+result+')');//eval把json字符串转换为json对象  {'errorMsg':'添加失败'}\r\n");
      out.write("\t\t\t\t\t //alert(result.errorMsg);\r\n");
      out.write("\t\t\t\t\t//if (result.errorMsg){//判断，如果错误信息不为空  js非null 非0 即true\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\tmsg: result.showInfo//提示信息\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t//} else {\r\n");
      out.write("\t\t\t\t\t   if(result.suc=='true'){\r\n");
      out.write("\t\t\t\t\t\t\t$('#dlg').dialog('close');\t\t// 关闭弹出框\r\n");
      out.write("\t\t\t\t\t\t\t$('#tt').datagrid('reload');\t// 刷新父窗口\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/sanjiliandong.js\"></script></head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \t<!-- 订单审核页面 -->\r\n");
      out.write("    <table id=\"tt\" class=\"easyui-datagrid\" title=\"前台订单\"\r\n");
      out.write("\t\tstyle=\"width:100%;height:560px\" pagination=\"true\" toolbar=\"#tb\"\r\n");
      out.write("\t\tdata-options=\"singleSelect:true,collapsible:true,url:'order/page.do?status1=1&overStore1=1',method:'get'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- hidden:true隐藏字段 sortable:true可以排序-->\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'id',width:80,hidden:true\" >订单id</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_mailnum',width:80,align:'center'\">订单号</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_time',width:100,align:'center',sortable:true\">订单时间</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_name',width:80,align:'center'\">发货人姓名</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_phone',width:80,align:'center'\">发货人电话</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_adr',width:85,align:'center'\">发货人地址</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_name',width:80,align:'center'\">收货人姓名</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_phone',width:80,align:'center'\">收货人电话</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_adr',width:85,align:'center'\">收货人地址</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_zipcode',width:50,align:'center'\">邮编</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_name',width:80,align:'center'\">物品名称</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_type',width:80,align:'center'\">物品类型</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_weight',width:80,align:'center'\">物品重量</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_remarks',width:80,align:'center'\">备注</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_status',width:80,align:'center'\" formatter=\"formatState\">物品状态</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_value',width:80,align:'center'\">物品价值</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_supportvalue',width:80,align:'center'\">保价金额</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_ifsupportvalue',width:80,align:'center'\">是否保价</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_cost',width:80,align:'center'\">费用</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'cost_type',width:80,align:'center'\">支付方式</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_now_store',width:80,align:'center'\">所在门店</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'over_store',width:80,align:'center'\">目的地门店</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 通过退单操作 -->\r\n");
      out.write("\t<div id=\"tb\" style=\"padding:3px\">\r\n");
      out.write("\t\t<a class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\" onclick=\"overStoreOrder()\">添加目的地</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 弹出添加更改页面 -->\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:800px;height:600px;padding:10px 20px\"\r\n");
      out.write("\t\tclosed=\"true\"  buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<div class=\"ftitle\">用户信息</div>\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>所在门店:</label>\r\n");
      out.write("\t\t\t\t\t\t<input id='stores' name=\"order_now_store\" readonly=\"readonly\"  required=\"required\"  >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>订单时间:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"order_time\" id=\"dd\" type=\"text\" readonly=\"readonly\" class=\"easyui-datebox\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>订单号:</label><!-- class=\"easyui-validatebox\" -->\r\n");
      out.write("\t\t\t\t\t\t<input name=\"order_mailnum\" id=\"ol\" readonly=\"readonly\" class=\"easyui-validatebox\" style=\"width:180px;height:30px\" validType=\"OrderNumber\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td><span id=\"mailnumInfo\"></span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>发货人姓名：</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"sender_name\" readonly=\"readonly\" required=\"required\" class=\"easyui-textbox\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>发货人电话：</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"sender_phone\" readonly=\"readonly\" required=\"required\" class=\"easyui-textbox\" validType=\"phone\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr><td>发货人地址:</td></tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"sender_adr\" readonly=\"readonly\" class=\"easyui-validatebox\" style=\"width:180px;height:30px\" required=\"required\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>收货人姓名:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"accepter_name\" readonly=\"readonly\" required=\"required\" class=\"easyui-textbox\"  >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>收货人电话:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"accepter_phone\" readonly=\"readonly\"required=\"required\" class=\"easyui-textbox\" validType=\"phone\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr><td>收货人地址:</td></tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"accepter_adr\" readonly=\"readonly\" required=\"required\"  class=\"easyui-validatebox\" style=\"width:180px;height:30px\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>邮编:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"accepter_zipcode\" readonly=\"readonly\" class=\"easyui-textbox\" validType=\"zipcode\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>物品名称:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"goods_name\" readonly=\"readonly\"class=\"easyui-textbox\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>物品类型:</label>\r\n");
      out.write("\t\t\t\t\t\t<!-- <input name=\"goods_type\" class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t\t\t\t\t\turl:'order/adr.do',\r\n");
      out.write("\t\t\t\t\t\t\tmethod:'get',\r\n");
      out.write("\t\t\t\t\t\t\tvalueField:'goods_type',\r\n");
      out.write("\t\t\t\t\t\t\ttextField:'goods_type',\r\n");
      out.write("\t\t\t\t\t\t\tpanelHeight:'auto'\r\n");
      out.write("\t\t\t\t\t\t\"> -->\r\n");
      out.write("\t\t\t\t\t    <select id=\"cc\" class=\"easyui-combobox\"readonly=\"readonly\" name=\"goods_type\" style=\"width:150px;\">\r\n");
      out.write("\t\t\t\t\t        <option value=\"衣服\">衣服</option>\r\n");
      out.write("\t\t\t\t\t        <option>食品</option>\r\n");
      out.write("\t\t\t\t\t        <option>数码</option>\r\n");
      out.write("\t\t\t\t\t        <option>饰品</option>\r\n");
      out.write("\t\t\t\t\t        <option>其他</option>\r\n");
      out.write("\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>物品重量（Kg）:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"goods_weight\" readonly=\"readonly\"  class=\"easyui-textbox\" validType=\"weight\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>备注:</label>\r\n");
      out.write("\t\t\t\t\t\t<!-- <input name=\"goods_remarks\" class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t\t\t\t\t\turl:'order/adr.do',\r\n");
      out.write("\t\t\t\t\t\t\tmethod:'get',\r\n");
      out.write("\t\t\t\t\t\t\tvalueField:'goods_remarks',\r\n");
      out.write("\t\t\t\t\t\t\ttextField:'goods_remarks',\r\n");
      out.write("\t\t\t\t\t\t\tpanelHeight:'auto'\r\n");
      out.write("\t\t\t\t\t\t\"> -->\r\n");
      out.write("\t\t\t\t\t\t<select id=\"cc\" class=\"easyui-combobox\" readonly=\"readonly\" name=\"goods_remarks\" style=\"width:150px;\">\r\n");
      out.write("\t\t\t\t\t        <option value=\"防压防挤\">防压防挤</option>\r\n");
      out.write("\t\t\t\t\t        <option>防水防潮</option>\r\n");
      out.write("\t\t\t\t\t        <option>添加填充物</option>\r\n");
      out.write("\t\t\t\t\t        <option>其他</option>\r\n");
      out.write("\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<!-- <td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>物品状态:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"goods_status\" class=\"easyui-validatebox\" >\r\n");
      out.write("\t\t\t\t\t</td> -->\r\n");
      out.write("\t\t\t\t\t<input name=\"goods_status\" id=\"goodsStatus\" readonly=\"readonly\" class=\"easyui-validatebox\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>物品价值（元）:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"goods_value\" readonly=\"readonly\" class=\"easyui-textbox\" validType=\"value\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>保价金额（元）:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"goods_supportvalue\" readonly=\"readonly\" class=\"easyui-textbox\" validType=\"supportvalue\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>是否保价:</label>\r\n");
      out.write("\t\t\t                <input type=\"radio\" readonly=\"readonly\" name=\"goods_ifsupportvalue\" value=\"0\">否</input>\r\n");
      out.write("\t\t\t                <input type=\"radio\" readonly=\"readonly\" name=\"goods_ifsupportvalue\" value=\"1\">是</input>          \r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>费用（元）:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"goods_cost\" readonly=\"readonly\" class=\"easyui-textbox\" validType=\"cost\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>支付方式:</label>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"cc\" class=\"easyui-combobox\" readonly=\"readonly\" name=\"cost_type\" style=\"width:150px;\">\r\n");
      out.write("\t\t\t\t\t        <option value=\"网上付款\">网上付款</option>\r\n");
      out.write("\t\t\t\t\t        <option>现金支付</option>\r\n");
      out.write("\t\t\t\t\t        <option>邮寄到付</option>\r\n");
      out.write("\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>目的地门店:</label>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><select id=\"province\" style=\"width:150px;height:30px\"></select></td> \r\n");
      out.write("\t\t\t\t\t<td><select id=\"city\" style=\"width:150px;height:30px\"></select></td>\r\n");
      out.write("\t\t\t\t\t<td><select id=\"area\" style=\"width:150px;height:30px\"></select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"over_store\" id=\"address\" class=\"easyui-validatebox\" style=\"width:180px;height:30px\" required=\"required\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 添加页面的保存按钮 -->\t\r\n");
      out.write("\t<!-- 添加页面的保存按钮 -->\t\t\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t\t<a  id=\"sbt\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" onclick=\"saveUser()\"> 保存</a>\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlg').dialog('close')\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
