/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-22 07:24:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backStage.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class lookOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t\r\n");
      out.write("\t");

		String path = request.getContextPath();
		String basePath = request.getScheme() + "://"
				+ request.getServerName() + ":" + request.getServerPort()
				+ path + "/";
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\t<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>My JSP 'lookOrder.jsp' starting page</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t//给单数字状态换成汉字状态\r\n");
      out.write("\t\tfunction formatState(value,row,index){//val 当前列的值  row取当前行的值\r\n");
      out.write("\t    \tif (row.goods_status==1){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">待审核</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==2){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">审核通过</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==3){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">入库</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==4){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">装配</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==5){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">出库</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==6){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">目的地站</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==6){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">已签收</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==66){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">退单</span>';\r\n");
      out.write("\t    \t} \r\n");
      out.write("  \t \t }\r\n");
      out.write("  \t \t //查询下拉框\r\n");
      out.write("\t\tfunction doSearchByStatus(){\r\n");
      out.write("\t\t\t//获取option的值\r\n");
      out.write("\t\t\tvar s=$('#goods_status').val();\r\n");
      out.write("\t\t\t//alert(s);\r\n");
      out.write("\t\t\tif(s=='待审核'){\r\n");
      out.write("\t\t\t \t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus1: 1\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (s=='审核通过'){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus2: 2\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (s=='入库'){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus3: 3\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (s=='装配'){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus4: 4\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (s=='出库'){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus5: 5\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (s=='目的地站'){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus6: 6\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (s=='已签收'){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus6: 7\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (s=='退单'){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tstatus66: 66\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t //通过订单号查询方法\r\n");
      out.write("\t\t function doSearchByMailnum(){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\torder_mailnum: $('#order_mailnum').val()\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<table id=\"tt\" class=\"easyui-datagrid\" title=\"订单列表\"\r\n");
      out.write("\t\tstyle=\"width:100%;height:560px\" pagination=\"true\" toolbar=\"#tb\"\r\n");
      out.write("\t\tdata-options=\"singleSelect:true,collapsible:true,url:'order/page.do',method:'post'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- hidden:true隐藏字段 sortable:true可以排序-->\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'id',width:80,hidden:true\" >订单id</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_mailnum',width:80,align:'center'\">订单号</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_time',width:100,align:'center',sortable:true\">订单时间</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_name',width:80,align:'center'\">发货人姓名</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_phone',width:80,align:'center'\">发货人电话</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_adr',width:85,align:'center'\">发货人地址</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_name',width:80,align:'center'\">收货人姓名</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_phone',width:80,align:'center'\">收货人电话</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_adr',width:85,align:'center'\">收货人地址</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_zipcode',width:50,align:'center'\">邮编</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_name',width:80,align:'center'\">物品名称</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_type',width:80,align:'center'\">物品类型</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_weight',width:80,align:'center'\">物品重量</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_remarks',width:80,align:'center'\">备注</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_status',width:80,align:'center'\" formatter=\"formatState\">物品状态</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_value',width:80,align:'center'\">物品价值</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_supportvalue',width:80,align:'center'\">保价金额</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_ifsupportvalue',width:80,align:'center'\">是否保价</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_cost',width:80,align:'center'\">费用</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'cost_type',width:80,align:'center'\">支付方式</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_now_store',width:80,align:'center'\">所在门店</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 页面分状态查询功能 -->\r\n");
      out.write("\t<div id=\"tb\" style=\"padding:3px\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span>状态:</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"goods_status\" style=\"line-height:26px;border:1px solid #ccc\">\r\n");
      out.write("\t\t\t\t\t\t\t<option >待审核</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option >审核通过</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option >入库</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option >装配</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option >出库</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>目的地站</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option >已签收</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>退单</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<a   class=\"easyui-linkbutton\" plain=\"true\" onclick=\"doSearchByStatus()\">查询</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span>订单号:</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"order_mailnum\" style=\"line-height:26px;border:1px solid #ccc\">\r\n");
      out.write("\t\t\t\t\t\t<a   class=\"easyui-linkbutton\" plain=\"true\" onclick=\"doSearchByMailnum()\">查询</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
