/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 07:22:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backStage.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class overStoreOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'inkuOrder.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//给单数字状态换成汉字状态\r\n");
      out.write("\t\tfunction formatState(value,row,index){//val 当前列的值  row取当前行的值\r\n");
      out.write("\t    \tif (row.goods_status==1){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">待审核</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==2){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">审核通过</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==3){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">入库</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==4){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">装配</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==5){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:blue;\">出库</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==6){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">目的地站</span>';\r\n");
      out.write("\t    \t} else if (row.goods_status==6){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">已签收</span>';\r\n");
      out.write("\t    \t}  else if (row.goods_status==66){\r\n");
      out.write("\t    \t\treturn '<span style=\"color:red;\">退单</span>';\r\n");
      out.write("\t    \t} \r\n");
      out.write("  \t \t }\r\n");
      out.write("  \t \t \t//目的地方法\r\n");
      out.write("\t\tfunction overStoreOrder(){\r\n");
      out.write("\t\t\t\tvar row = $('#tt').datagrid('getChecked');//如果这一行被选中\r\n");
      out.write("\t\t\t\tif (row){\r\n");
      out.write("\t\t\t\t var idsStr=\"\";\r\n");
      out.write("\t\t\t\t for(var i=0;i<row.length;i++){\r\n");
      out.write("\t\t\t\t     idsStr+=row[i].id+\",\";//拿到这一行想要传往前台的值，拼接为字符串，以逗号隔开\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t\t// alert(order_ids);\r\n");
      out.write("\t\t\t\t $.messager.confirm('Confirm','确认到达目的地站吗?',function(r){\r\n");
      out.write("\t\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\t   //jquery的ajax操作  $.get(地址，参数，回调函数，返回值类型)\r\n");
      out.write("\t\t\t\t\t   //  $.post(地址，参数，回调函数，返回值类型)\r\n");
      out.write("\t\t\t\t\t   //alert(\"111\");\r\n");
      out.write("\t\t\t\t\t\t$.post('order/overStoreOrder.do',{idsStr:idsStr},function(result){\r\n");
      out.write("\t\t\t\t\t\t\t//alert(result);\r\n");
      out.write("\t\t\t\t\t\t\tif (result.suc=='true'){\r\n");
      out.write("\t\t\t\t\t\t\t  //  alert(1111);\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#tt').datagrid('reload');\t// 更新父窗口\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({\t// show error message\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle: '信息提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg: result.showInfo\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({\t// show error message\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle: '错误提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg: result.showInfo\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},'json');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t   \t\t\t\t$.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\tmsg: '请至少选中一行！！！'//提示信息\r\n");
      out.write("\t\t\t\t \t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("  \t \r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \t<!-- 订单审核页面 -->\r\n");
      out.write("    <table id=\"tt\" class=\"easyui-datagrid\" title=\"订单审核\"\r\n");
      out.write("\t\tstyle=\"width:100%;height:560px\" pagination=\"true\" toolbar=\"#tb\"\r\n");
      out.write("\t\tdata-options=\"singleSelect:false,collapsible:true,url:'order/page.do?status2=2&overStore=1',method:'get'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- hidden:true隐藏字段 sortable:true可以排序-->\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'ck',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'id',width:80,hidden:true\" >订单id</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_mailnum',width:80,align:'center'\">订单号</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_time',width:100,align:'center',sortable:true\">订单时间</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_name',width:80,align:'center'\">发货人姓名</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_phone',width:80,align:'center'\">发货人电话</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sender_adr',width:85,align:'center'\">发货人地址</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_name',width:80,align:'center'\">收货人姓名</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_phone',width:80,align:'center'\">收货人电话</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_adr',width:85,align:'center'\">收货人地址</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'accepter_zipcode',width:50,align:'center'\">邮编</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_name',width:80,align:'center'\">物品名称</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_type',width:80,align:'center'\">物品类型</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_weight',width:80,align:'center'\">物品重量</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_remarks',width:80,align:'center'\">备注</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_status',width:80,align:'center'\" formatter=\"formatState\">物品状态</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_value',width:80,align:'center'\">物品价值</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_supportvalue',width:80,align:'center'\">保价金额</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_ifsupportvalue',width:80,align:'center'\">是否保价</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'goods_cost',width:80,align:'center'\">费用</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'cost_type',width:80,align:'center'\">支付方式</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_now_store',width:80,align:'center'\">所在门店</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 通过退单操作 -->\r\n");
      out.write("\t<div id=\"tb\" style=\"padding:3px\">\r\n");
      out.write("\t\t<a class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\" onclick=\"overStoreOrder()\">目的地站</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
