/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 06:39:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backStage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class role_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>角色表</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("     <table id=\"tt\" class=\"easyui-datagrid\"   title=\"员工信息列表列表\" style=\"width:100%; \"\r\n");
      out.write("\t\t\tpagination=\"true\" fitColumns=\"true\" toolbar=\"#tb\" iconCls=\"icon-more\"  \tdata-options=\"singleSelect:true,collapsible:true,url:'emp/roleList.do',method:'post'\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'id',width:80,align:'center',sortable:true\"  >序号</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'role',width:100,align:'center'\" sortable=\"true\">名字</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'description',width:80,align:'center'\">性别</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!--搜素，添加 ，删除，查询  -->\r\n");
      out.write("\t\t<div id=\"tb\" style=\"padding:3px\">\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\" onclick=\"givePower()\">授权</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<span>员工名:</span>\r\n");
      out.write("\t\t\t<input id=\"ename\" style=\"line-height:26px;border:1px solid #ccc\">\r\n");
      out.write("\t\t\t<span>用户名:</span>\r\n");
      out.write("\t\t\t<input id=\"username\" style=\"line-height:26px;border:1px solid #ccc\">\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" plain=\"true\" onclick=\"doSearch()\">查询</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--更新，添加框  -->\r\n");
      out.write("\t\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px;height:280px;padding:10px 20px\"\r\n");
      out.write("\t\tclosed=\"true\"  buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t\t<div class=\"ftitle\">员工信息</div>\r\n");
      out.write("\t\t\t<form id=\"fm\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t<label>id:</label>\r\n");
      out.write("\t\t\t\t\t<input name=\"id\" class=\"easyui-validatebox\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t<label>角色:</label>\r\n");
      out.write("\t\t\t\t\t<input name=\"role\" class=\"easyui-validatebox\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t<label>角色描述:</label>\r\n");
      out.write("\t\t\t\t\t<input name=\"description\" class=\"easyui-validatebox\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" iconCls=\"icon-ok\" onclick=\"saveUser()\"> 保存</a>\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlg').dialog('close')\">取消</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--...................................................  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"dlga\" class=\"easyui-dialog\" style=\"width:400px;height:400px;padding:10px 20px;top:50px;\"\r\n");
      out.write("\t\tclosed=\"true\"  buttons=\"#dlg-buttonsa\">\r\n");
      out.write("\t\t\t<form id=\"fma\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t<label>角色名:</label>\r\n");
      out.write("\t\t\t\t\t<input name=\"role\" class=\"easyui-validatebox\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t <input name=\"id\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t <input id=\"powerIds\" name=\"powerIds\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t<label>权限选择:</label>\r\n");
      out.write("\t\t\t\t  <div class=\"easyui-panel\" style=\"padding:5px\">\r\n");
      out.write("\t\t\t\t\t  <ul id=\"ttree\" class=\"easyui-tree\" data-options=\"method:'get',animate:true,checkbox:true\"></ul>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"dlg-buttonsa\">\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" iconCls=\"icon-ok\" onclick=\"saveRoleAndPowers()\"> 保存</a>\r\n");
      out.write("\t\t\t<a   class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlga').dialog('close')\">取消</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t //弹出授权框\r\n");
      out.write("\t\tfunction givePower(){\r\n");
      out.write("\t\t  var row = $('#tt').datagrid('getSelected');\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\tif (row){\r\n");
      out.write("\t\t          //动态给树添加url\r\n");
      out.write("\t\t\t\t  $(\"#ttree\").tree({\r\n");
      out.write("\t\t\t\t      url:'power/checkedTree.do?roleId='+row.id\r\n");
      out.write("\t\t\t\t     //url:'jsp/role/tree_data1.json'\r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t \t$('#fma').form('clear');\r\n");
      out.write("\t\t\t \t\t//$('#ttree').tree('clear');\r\n");
      out.write("\t\t\t   \t$('#dlga').dialog('open').dialog('setTitle','授权');\r\n");
      out.write("\t\t\t   \t$('#fma').form('load',row);\r\n");
      out.write("\t\t   \t}else{\r\n");
      out.write("\t\t   \t   $.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\tmsg: '请至少选中一行！！！'//提示信息\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t   \t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t //保存授权\r\n");
      out.write("\t\t function saveRoleAndPowers(){\r\n");
      out.write("\t\t        //获取选中的所有节点\r\n");
      out.write("\t\t\t    var nodes = $('#ttree').tree('getChecked');\r\n");
      out.write("\t\t\t\tvar s = '';\r\n");
      out.write("\t\t\t\t//循环每一个节点\r\n");
      out.write("\t\t\t\tfor(var i=0; i<nodes.length; i++){\r\n");
      out.write("\t\t\t\t\tif (s != '') s += ',';\r\n");
      out.write("\t\t\t\t\ts += nodes[i].id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//赋值，目的向服务器传送数据\r\n");
      out.write("\t\t\t\t$(\"#powerIds\").val(s);\r\n");
      out.write("\t\t\t\t//alert(s);\r\n");
      out.write("\t\t\t\t//提交form表单\r\n");
      out.write("\t\t\t\t$('#fma').form('submit',{//给form表单绑定submit事件\r\n");
      out.write("\t\t\t\t\t\turl: \"emp/saveRoleAndPower.do\",//请求的url地址\r\n");
      out.write("\t\t\t\t\t\tonSubmit: function(){//对form表单校验\r\n");
      out.write("\t\t\t\t\t\t\treturn $(this).form('validate');\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(result){//数据保存后的回调函数\r\n");
      out.write("\t\t\t\t\t\t\tvar result = eval('('+result+')');//eval把json字符串转换为json对象  {'errorMsg':'添加失败'}\r\n");
      out.write("\t\t\t\t\t\t\t //alert(result.errorMsg);\r\n");
      out.write("\t\t\t\t\t\t\t//if (result.errorMsg){//判断，如果错误信息不为空  js非null 非0 即true\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg: result.showInfo//提示信息\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t//} else {\r\n");
      out.write("\t\t\t\t\t\t\t   if(result.suc=='true'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#dlga').dialog('close');\t\t// 关闭弹出框\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#tt').datagrid('reload');\t// 刷新父窗口\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t /*.....................................  */\r\n");
      out.write("\t\t//查询方法\r\n");
      out.write("\t\t  function doSearch(){\r\n");
      out.write("\t\t\t\t$('#tt').datagrid('load',{\r\n");
      out.write("\t\t\t\t\tename: $('#ename').val(),\r\n");
      out.write("\t\t\t\t\tusername: $('#username').val()\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t //弹出添加方法\r\n");
      out.write("\t\t function newUser(){\r\n");
      out.write("\t\t\t$('#dlg').dialog('open').dialog('setTitle','添加用户');\r\n");
      out.write("\t\t\t$('#fm').form('clear');\r\n");
      out.write("\t\t\turl = 'emp/add.do';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//弹出更新方法\r\n");
      out.write("\t\tfunction editUser(){\r\n");
      out.write("\t\t   //获取选中行\r\n");
      out.write("\t\t   var row = $('#tt').datagrid('getSelected');\r\n");
      out.write("\t\t\tif (row){\r\n");
      out.write("\t\t\t  //alert(row.ename);\r\n");
      out.write("\t\t\t     //弹出框\r\n");
      out.write("\t\t\t\t$('#dlg').dialog('open').dialog('setTitle','更新车辆');\r\n");
      out.write("\t\t\t\t//加载数据 根据datagrid里面的field的名称和form表单的名称必须一致\r\n");
      out.write("\t\t\t\t//alert(\"111\");\r\n");
      out.write("\t\t\t\t$('#fm').form('load',row);\r\n");
      out.write("\t\t\t\t//alert(\"222\");\r\n");
      out.write("\t\t\t\turl = 'emp/update.do?id='+row.id;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t     $.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\tmsg: '请至少选中一行！！！'//提示信息\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//保存操作(添加和保存使用的一个方法)\r\n");
      out.write("\t\tfunction saveUser(){\r\n");
      out.write("\t\t\t$('#fm').form('submit',{//给form表单绑定submit事件\r\n");
      out.write("\t\t\t\turl: url,//请求的url地址\r\n");
      out.write("\t\t\t\tonSubmit: function(){//对form表单校验\r\n");
      out.write("\t\t\t\t\treturn $(this).form('validate');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(result){//数据保存后的回调函数\r\n");
      out.write("\t\t\t\t\tvar result = eval('('+result+')');//eval把json字符串转换为json对象  {'errorMsg':'添加失败'}\r\n");
      out.write("\t\t\t\t\t //alert(result.errorMsg);\r\n");
      out.write("\t\t\t\t\t//if (result.errorMsg){//判断，如果错误信息不为空  js非null 非0 即true\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\tmsg: result.showInfo//提示信息\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t//} else {\r\n");
      out.write("\t\t\t\t\t   if(result.suc=='true'){\r\n");
      out.write("\t\t\t\t\t\t\t$('#dlg').dialog('close');\t\t// 关闭弹出框\r\n");
      out.write("\t\t\t\t\t\t\t$('#tt').datagrid('reload');\t// 刷新父窗口\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//删除数据\r\n");
      out.write("\t\tfunction destroyUser(){\r\n");
      out.write("\t\t    //获取选中行\r\n");
      out.write("\t\t\tvar row = $('#tt').datagrid('getSelected');\r\n");
      out.write("\t\t\tif (row){\r\n");
      out.write("\t\t\t\t$.messager.confirm('Confirm','确认删除吗?',function(r){\r\n");
      out.write("\t\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\t   //jquery的ajax操作  $.get(地址，参数，回调函数，返回值类型)\r\n");
      out.write("\t\t\t\t\t   //  $.post(地址，参数，回调函数，返回值类型)\r\n");
      out.write("\t\t\t\t\t\t$.post('emp/delete.do',{id:row.id},function(result){\r\n");
      out.write("\t\t\t\t\t\t\tif (result.success){\r\n");
      out.write("\t\t\t\t\t\t\t  //  alert(1111);\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#tt').datagrid('reload');\t// 更新父窗口\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({\t// show error message\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle: '错误提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg: result.errorMsg\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},'json');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t   $.messager.show({//easyui封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '信息提示',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\tmsg: '请至少选中一行！！！'//提示信息\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
