/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 05:08:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.forwardStage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>马六甲物流有限公司</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=1200,user-scalable=yes\"><!--最大宽度1200px 允许用户缩放-->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/bootstrap.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/tf.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/tf.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style1.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/style1.css\" />\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tp{color:red;}\r\n");
      out.write("\t\t</style>\t\r\n");
      out.write("  </head> \r\n");
      out.write("  <body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, true);
      out.write("\r\n");
      out.write("\t\t<div class=\"about-us\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cebian\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"imgs/ww.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/ww.png\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>关于我们</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>ABOUT US</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ab-cebian\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cebian-lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>全国服务热线 :</strong></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><span>0512-57995109</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>TEL:</strong>0512-57995109</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>QQ:</strong>1927732720</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bread-xie\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forward/index.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/index.jsp\">首页</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forward/about.do\">关于我们</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"about-jianjie\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>马六甲物流有限公司是一家经工商、交通、税务等有关部门审核通过签发《企业经营许可证》《道路运输许可证》《税务登记证》》《组织机构代码证》批准专业从事综合性的物流企业。公司凭着稳定、可靠、安全的运营网络、科学的资源整合、先进的管理技术，可为各类企业、个人、在校学生、提供全方位的物流服务，我们将一如既往地坚持“以客为本、服务领先” 的经营理念，为客户提供门对门、仓对仓的一站式服务。</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>公司凭着稳定、可靠、安全的运营网络、科学的资源整合、先进的管理技术，可为各类企业、个人、在校学生、提供全方位的物流服务，我们将一如既往地坚持“以客为本、服务领先” 的经营理念，为客户提供门对门、仓对仓的一站式服务。</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>马六甲物流有限公司是集代理、物流配送、航空速递、公路运输、铁路运输、仓储、城际配送于一体，跨区域、网络化、信息化、智能化、具有供应链管理能力的综合性物流公司、准点发车、准点到达、保证低价、全程高速，安全、快速、送货及时。</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>多年来，公司在全体员工努力下，抢抓机遇、敢想敢为，艰苦创业、与时俱进，以果敢的胆识，通过启动社会资源，与不拘一格提拔人才，成功走出一条具有凯瑞通特色的发展之路。公司以“团结拼搏、做强做大做久”的企业精神；以“城际网络运输”的运作模式实现了从零起步的跨越式发展，创造了产值连年翻番、效益连年增长、服务连年优化、实力连年攀高的辉煌业绩，力争五年内成为国内具特色企业。</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "forward/bottom.do", out, true);
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
