/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 06:51:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.forwardStage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class chaxundingdan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>马六甲物流有限公司</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.search_box{\r\n");
      out.write("\t\t\t\t    width: 430px;\r\n");
      out.write("\t\t\t\t    float: left;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t.zi{\r\n");
      out.write("  \t\t\t\t\tcolor:green;\r\n");
      out.write("  \t\t\t}\t\t\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=1200,user-scalable=yes\"><!--最大宽度1200px 允许用户缩放-->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/bootstrap.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/tf.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/tf.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/style1.css\" />\t\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("\t\t//给但数字转化成汉字\r\n");
      out.write("\t\t//给单数字状态换成汉字状态\r\n");
      out.write("\t\t $(function(){\r\n");
      out.write("\t\t \tvar status=$(\"#goods_status\").val();\r\n");
      out.write("\t\t \tif(status==1){\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").val(\"待审核\");\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").css(\"color\",\"red\");\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \tif(status==2){\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").val(\"审核通过\");\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").css(\"color\",\"blue\");\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \tif(status=='3'){\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").val(\"入库\");\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").css(\"color\",\"blue\");\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \tif(status==4){\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").val(\"装配\");\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").css(\"color\",\"blue\");\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \tif(status==5){\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").val(\"已签收\");\r\n");
      out.write("\t\t \t\t$(\"#goods_status\").css(\"color\",\"green\");\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t });\r\n");
      out.write("\t    \t\r\n");
      out.write("\t</script>\r\n");
      out.write(" \t<script type=\"text/javascript\">\r\n");
      out.write(" \t\tfunction turn(){\r\n");
      out.write("\t\t\tlocation.href=\"forward/dingdanchaxun.do\"\r\n");
      out.write(" \t\t};\r\n");
      out.write(" \t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "forward/top.do", out, true);
      out.write("\r\n");
      out.write("  \t<form action=\"qtorder/select.do\" method=\"post\">\t\r\n");
      out.write("\t\t<div class=\"about-us\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cebian\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"imgs/ww.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/ww.png\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>订单查询</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>ORDERED</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ab-cebian\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cebian-lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>全国服务热线 :</strong></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><span>0512-57995109</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>TEL:</strong>0512-57995109</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>QQ:</strong>1927732720</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bread-xie\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forward/index.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/index.jsp\">首页</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forward/xiadan.do\">网上下单</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forward/dingdanchaxun.do\">在线查询</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"about-jianjie clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">订单号<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"order_mailnum\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].order_mailnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">物品状态<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"goods_status\" id=\"goods_status\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].goods_status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">货物名称<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"goods_name\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].goods_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">发货人姓名<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sender_name\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].sender_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">发货人手机号码<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sender_phone\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].sender_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">发货详细地址<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sender_adr\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].sender_adr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">收货人姓名<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"accepter_name\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].accepter_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">收货人手机号<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"accepter_phone\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].accepter_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zi\">收货详细地址<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"accepter_adr\" id=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].accepter_adr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><span ></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-primary\" value=\"返回查询列表\" onclick=\"return turn()\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "forward/bottom.do", out, true);
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
