/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 05:07:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.forwardStage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>马六甲物流有限公司</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=1200,user-scalable=yes\"><!--最大宽度1200px 允许用户缩放-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/bootstrap.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/cubeportfolio.min.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/cubeportfolio.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/tf.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/tf.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("\t\t<div class=\"index-top\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse site-navbar\">\r\n");
      out.write("\t\t\t<div class=\"about-nav-py\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed jicheng\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("\t\t                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t               </button>\r\n");
      out.write("\t\t               <a class=\"navbar-brand\" href=\"\"><img alt=\"Brand\" src=\"imgs/logo.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/logo.png\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"navbar\" class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav nav-top-quanju\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forward/index.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/index.jsp\" class=\"active-daohang\">网站首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forward/about.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/about.jsp\">关于我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forward/yewu.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/yewu.jsp\">业务范围</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forward/xiadan.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/xiadan.jsp\">网上下单</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forward/dingdanchaxun.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/xiadan.jsp\">订单查询</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forward/contact.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/contact.jsp\">联系我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--/.nav-collapse -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div id=\"wrapper\">\r\n");
      out.write("\t\t\t<div class=\"fullwidthbanner-container\">\r\n");
      out.write("\t\t\t\t<div class=\"fullwidthbanner\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li data-transition=\"3dcurtain-horizontal\" data-slotamount=\"15\" data-masterspeed=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"imgs/slide3.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/slide3.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li data-transition=\"papercut\" data-slotamount=\"15\" data-masterspeed=\"300\" data-link=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"imgs/slide2.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/slide2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li data-transition=\"turnoff\" data-slotamount=\"15\" data-masterspeed=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"imgs/slide1.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/slide1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li data-transition=\"turnoff\" data-slotamount=\"15\" data-masterspeed=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"imgs/slide4.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/slide4.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"banner-container\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"banner-wenzi\">\r\n");
      out.write("\t\t\t\t\t\t<h2>致力于：国际空运、海运、陆运</h2>\r\n");
      out.write("\t\t\t\t\t\t<div>等多项物流</div>\r\n");
      out.write("\t\t\t\t\t\t<p>安全第一 . 速度第一 . 诚信第一 . 技术第一</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"index-about\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"index-about-top\">\r\n");
      out.write("\t\t\t\t\t\t<strong>S</strong>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<span>服务项目</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"index-span\">ERVICE ITEMS</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>安全第一 · 速度第一 · 诚信第一 · 技术第一</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"index-fuwu\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw1.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw1.png\" class=\"fuw1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>整车运输</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>拥有解放、东风、五十铃、康明斯等格式运输车辆几百部</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"index-fuwu\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw2.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw2.png\" class=\"fuw1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>仓储运输</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>领先的信息系统，全程可视，让您随时掌握每单业务的准确进度</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"index-fuwu\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw3.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw3.png\" class=\"fuw1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>空车配送</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>具有多温控组合运输，配送能力和异化服务的运输产品及模式</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"index-fuwu\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"imgs/fuw4.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/fuw4.png\" class=\"fuw1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>安全包装</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>专业从事国内各地货物运输服务，有着严谨的运输组织</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"index-about\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"index-about-top\">\r\n");
      out.write("\t\t\t\t\t\t<strong>A</strong>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<span>关于我们</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"index-span\">BOUT US</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>安全第一 · 速度第一 · 诚信第一 · 技术第一</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"index-ab-bj\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"imgs/ab.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/ab.png\"/>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>公司介绍</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>COMPANY INTRODUCTION</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>马六甲物流有限公司成立于1985年，是国务院国资委监管的大型企业集团——某某物流集团有限公司的成员企业。公司定位于供应链物流管理一体化服务提供商，提供铁路和公路运输、公路-铁路-水运联运、国际货运代理、仓储、配送、生产和销售的供应链管理、供应链金融等综合物流服务，在烟酒快速消费品、装备制造业等行业领域具备了成熟的服务能力和标准体系，形成了独特的竞争优势。​</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-ab-gd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forward/about.do\">查看更多</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"service-index\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"index-about-top\">\r\n");
      out.write("\t\t\t\t\t\t<strong>S</strong>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<span>服务领域</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"index-span\">ERVICE AREA</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>安全第一 · 速度第一 · 诚信第一 · 技术第一</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row index-pro\">\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix index-pro-list one\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"service-index-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/5.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/5.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/5.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/5.jpg\" class=\"img-service\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>公路运输</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>发展汽运服务，充分运用各式运输车辆为客户提供全方位、灵活的干线运输服务。为区域性连锁、门到门、特殊性、专业性客户提供联动服务</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"service-index-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/6.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/6.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/6.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/6.jpg\" class=\"img-service\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>海陆运输</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>无论您需要什么物流服务，需要您做的只是想起我们。我们坚持：不懈努力 追求卓越前进的道路没有终点，为您打造拥有海上运输服务</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"service-index-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/7.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/7.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/7.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/7.jpg\" class=\"img-service\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>铁路运输</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>时速达160公里/小时特快行邮专列属中国最快的铁路货运专列，按直达特快客运列车等级运行，为高附加值产品提供直达快运服务</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"service-index-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/8.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/8.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/8.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/8.jpg\" class=\"img-service\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>航空运输</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>办理各类货物的航空运输，包括集中托运、门到门运输等；提供空、陆空联运等多式联运；承办文件、样品、小件物品的一条龙运输服务</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"index-pro-gd\">\r\n");
      out.write("\t\t\t\t\t<a    href=\"forward/about.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/product.jsp\">查看更多</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"index-lianxi\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"lianxi-p\"><span>联系方式</span></p>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"imgs/dai.jpg\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/dai.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<p><i></i><strong>地址:</strong>昆山市前进西路301号</p>\r\n");
      out.write("\t\t\t\t\t\t<p><i></i><strong>邮箱:</strong>hx_hou@geding.net</p>\r\n");
      out.write("\t\t\t\t\t\t<p><i></i><strong>电话:</strong>0512-87818757 </p>\r\n");
      out.write("\t\t\t\t\t\t<p><i></i><strong>手机:</strong>15995656015</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"qtorder/select.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"lianxi-p\"><span>在线查询</span></p>\r\n");
      out.write("\t\t\t\t\t\t<p><strong>产品名称:</strong>&nbsp;&nbsp;&nbsp;<input type=\"\" name=\"\" id=\"\"  /></p>\r\n");
      out.write("\t\t\t\t\t\t<p><strong>留言备注:</strong>&nbsp;&nbsp;&nbsp;<textarea type=\"\" name=\"\" id=\"\"  /></textarea></p>\r\n");
      out.write("\t\t\t\t\t\t<p><strong>联系电话:</strong>&nbsp;&nbsp;&nbsp;<input type=\"\" name=\"\" id=\"\"  /></p>\r\n");
      out.write("\t\t\t\t\t\t<p><strong>订单号:&nbsp;&nbsp;&nbsp;&nbsp;</strong>&nbsp;&nbsp;&nbsp;<input type=\"\" name=\"order_mailnum\" id=\"\" msg=\"订单号\"/></p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tijiao\"><input type=\"submit\" value=\"查询\" onclick=\"return checkOrder()\"></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-ul\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"forward/index.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/index.jsp\">网站首页</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"forward/about.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/about.jsp\">关于我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"forward/yewu.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/yewu.jsp\">业务范围</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"forward/xiadan.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/xiadan.jsp\">网上下单</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"forward/chaxundingdan.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/xiadan.jsp\">订单查询</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"forward/contact.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/contact.jsp\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"copy-r\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>© 2017 马六甲有限公司 版权所有 | ICP备0000000号</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"css/jquery.min.js\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"css/bootstrap.min.js\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"css/jquery-1.8.3.min.js\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"css/jquery.banner.revolution.min.js\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/js/jquery.banner.revolution.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"css/banner.js\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/js/banner.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("  \t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction checkOrder()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t     var num=0;\r\n");
      out.write("\t\t     var str=\"\";\r\n");
      out.write("\t\t     $(\"input[name$='order_mailnum']\").each(function(n){\r\n");
      out.write("\t\t          if($(this).val()==\"\")\r\n");
      out.write("\t\t          {\r\n");
      out.write("\t\t               num++;\r\n");
      out.write("\t\t               str+=$(this).attr(\"msg\")+\"不能为空\";\r\n");
      out.write("\t\t          }\r\n");
      out.write("\t\t     });\r\n");
      out.write("\t\t     if(num>0)\r\n");
      out.write("\t\t     {\r\n");
      out.write("\t\t          alert(str);\r\n");
      out.write("\t\t          return false;\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t     else\r\n");
      out.write("\t\t     {\r\n");
      out.write("\t\t          return true;\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t}\r\n");
      out.write(" \r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".news-tab li\").click(function() {\r\n");
      out.write("\t\t\t\t$(this).siblings().removeClass('current');\r\n");
      out.write("\t\t\t\t$(this).addClass('current');\r\n");
      out.write("\t\t\t\t$('.news-container li').removeClass('one-li');\r\n");
      out.write("\t\t\t\t$('.news-container li').eq($(this).index()).addClass('one-li');\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\".pro-ul >li\").click(function(){\r\n");
      out.write("\t\t\t$(this).siblings().removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t$(\".index-pro >div\").removeClass(\"one\");\r\n");
      out.write("\t\t\t$(\".index-pro >div\").eq($(this).index()).addClass(\"one\")\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\".news-bufen .pro-ul >li\").click(function(){\r\n");
      out.write("\t\t\t$(this).siblings().removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t$(\".index-n >div\").removeClass(\"one\");\r\n");
      out.write("\t\t\t$(\".index-n >div\").eq($(this).index()).addClass(\"one\")\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//右侧返回顶部图标\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tvar icon = '<a class=\"gotoptop_icon\" id=\"gotoptop_icon\" href=\"#\" title=\"返回顶部\"></a>';\r\n");
      out.write("\t\t\t$(\"body\").append(icon);\r\n");
      out.write("\t\t\tvar $window = $(window);\r\n");
      out.write("\t\t\tvar $gotoptop_icon = $(\"#gotoptop_icon\");\r\n");
      out.write("\t\t\tvar $body = (window.opera) ? (document.compatMode == \"CSS1Compat\" ? $('jsp') : $('body')) : \t\t\t$('jsp,body'); // opera fix\r\n");
      out.write("\t\t\t$(window).bind('scroll resize', function() {\r\n");
      out.write("\t\t\t\tif($window.scrollTop() > 0) {\r\n");
      out.write("\t\t\t\t\t$gotoptop_icon.show();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$gotoptop_icon.hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$gotoptop_icon.bind('click', function() {\r\n");
      out.write("\t\t\t\t$body.animate({\r\n");
      out.write("\t\t\t\t\tscrollTop: '0px'\r\n");
      out.write("\t\t\t\t}, \"fast\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
