/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 05:08:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.forwardStage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.aaa.mvc.util.RandomCount;
import java.util.*;

public final class xiadan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>马六甲物流有限公司</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/css/bootstrap.css\" type=\"text/css\"></link>\r\n");
      out.write("\t\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=1200,user-scalable=yes\"><!--最大宽度1200px 允许用户缩放-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/bootstrap.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/tf.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/tf.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/css/style1.css\" />\r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \t<script type=\"text/javascript\"  src=\"resource/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("  \t\twindow.onload = function(){\r\n");
      out.write("\t\tfunction getDate(){\r\n");
      out.write("\t\tdebugger;\r\n");
      out.write("\t\tvar today = new Date();\r\n");
      out.write("\t\tvar date;\r\n");
      out.write("\t\tdate = (today.getFullYear()) +\"-\" + (today.getMonth() + 1 ) + \"-\" + today.getDate();\r\n");
      out.write("\t\treturn date;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.setInterval(function(){\r\n");
      out.write("\t\tdocument.getElementById(\"order_time\").value=getDate();\r\n");
      out.write("\t\t}, 1000);\r\n");
      out.write("\t\t} \r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\t\r\n");
      out.write("  \t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.fhsf{\r\n");
      out.write("\t\t\theight:68px;\r\n");
      out.write("\t\t\tweight:100px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#province{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#city{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#area{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#province1{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#city1{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#area1{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#province2{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#city2{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#area2{\r\n");
      out.write("\t\t\tweight:200px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("  \tfunction verify(){\r\n");
      out.write("        //获取form标签元素\r\n");
      out.write("        var form=document.getElementById('form');\r\n");
      out.write("        //获取form下元素下所有input标签\r\n");
      out.write("        var inputArray=form.getElementsByTagName(\"input\");\r\n");
      out.write("        var inputArrayLength=inputArray.length;\r\n");
      out.write("        //循环input元素数组\r\n");
      out.write("        for(var int=0;int<inputArrayLength;int++){\r\n");
      out.write("            //判断每个input元素的值是否为空\r\n");
      out.write("            if( inputArray[int].value==null || inputArray[int].value==''){\r\n");
      out.write("                alert('亲！*为必填项^_^');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        //如果所有Input标签的值都不为空的话\r\n");
      out.write("        alert('下单成功');\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("  \t\r\n");
      out.write("  \t//所属门店\r\n");
      out.write("  \t\t$(function(){\r\n");
      out.write("\t  \t\t$.post(\r\n");
      out.write("\t \t\t\t//url\r\n");
      out.write("\t \t\t\t\"order/getStore.do\",\r\n");
      out.write("\t \t\t\t//不携带参数\r\n");
      out.write("\t \t\t\t//{status3:3},\r\n");
      out.write("\t \t\t\t//回调函数\r\n");
      out.write("\t \t\t\tfunction(data){\r\n");
      out.write("\t\t\t\t\t//alert(data);\r\n");
      out.write("\t \t\t\t\tvar str = '';\r\n");
      out.write("\t \t\t\t\tif(data!=''){\r\n");
      out.write("\t \t\t\t\t\tfor(var i = 0;i<data.length;i++){\r\n");
      out.write("\t\t\t\t\t\t\tstr +=\"<option  value = '\"+data[i].store_name+\"'>\"+data[i].store_name+\"</option>\"\r\n");
      out.write("\t \t\t\t\t\t}\r\n");
      out.write("\t \t\t\t\t\t$(\"#nowStore\").append(str);\r\n");
      out.write("\t \t\t\t\t}\r\n");
      out.write("\t \t\t\t},\r\n");
      out.write("\t \t\t\t//数据类型\r\n");
      out.write("\t \t\t\t\"json\"\r\n");
      out.write("\t \t\t);\r\n");
      out.write("  \t});\r\n");
      out.write("  \t//发货人手机号码校验\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#phone\").blur(function(){\r\n");
      out.write("  \t\t\tvar phone = $(\"#phone\").val();\r\n");
      out.write("  \t\t\tvar phoneNum = /^1(?:3\\d|4[4-9]|5[0-35-9]|6[67]|7[013-8]|8\\d|9\\d)\\d{8}$/ ;\r\n");
      out.write("  \t\t\tif(phoneNum.test(phone)){\r\n");
      out.write("  \t\t\t\t\t$(\"#phoneSpan\").html(\"手机号格式填写正确\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t} else {\r\n");
      out.write("  \t\t\t\tif(phone==''||phone==null||phone=='null'){\r\n");
      out.write("  \t\t\t\t\t//alert(11);\r\n");
      out.write("  \t\t\t\t\t$(\"#phoneSpan\").html(\"手机号不可为空\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t} else {\r\n");
      out.write("\t  \t\t\t\t$(\"#phoneSpan\").html(\"手机号格式不正确,请填写正确的手机号格式!!\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t//收货人手机号校验\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#tel\").blur(function(){\r\n");
      out.write("  \t\t\tvar tel = $(\"#tel\").val();//blur失焦事件\r\n");
      out.write("  \t\t\tvar telPhone=/^1(?:3\\d|4[4-9]|5[0-35-9]|6[67]|7[013-8]|8\\d|9\\d)\\d{8}$/;//手机号码正则表达式\r\n");
      out.write("  \t\t\tif(telPhone.test(tel)){\r\n");
      out.write("  \t\t\t\t$(\"#telSpan\").html(\"手机号格式填写正确\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t}else{\r\n");
      out.write("  \t\t\t\tif(tel==''||tel==null||tel=='null'){\r\n");
      out.write("  \t\t\t\t\t//alert(11);\r\n");
      out.write("  \t\t\t\t\t$(\"#telSpan\").html(\"手机号不可为空\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}else{\r\n");
      out.write("  \t\t\t\t\t$(\"#telSpan\").html(\"手机号格式不正确,请填写正确的手机号格式\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t//邮编号码校验\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#zidcode\").blur(function(){\r\n");
      out.write("  \t\t\tvar postcode = $(\"#zidcode\").val();\r\n");
      out.write("  \t\t\tvar code =/[1-9]{1}(\\d+){5}/;\r\n");
      out.write("  \t\t\tif(code.test(postcode)){\r\n");
      out.write("  \t\t\t\t//alert(11)\r\n");
      out.write("  \t\t\t\t$(\"#codeSpan\").html(\"邮编格式正确\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t}else{\r\n");
      out.write("  \t\t\t\tif(postcode==''||postcode==null||postcode=='null'){//注意=不可为中文\r\n");
      out.write(" \t \t\t\t\t$(\"#codeSpan\").html(\"邮编号码不可为空\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}else{\r\n");
      out.write("  \t\t\t\t\t$(\"#codeSpan\").html(\"邮编格式不正确\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t//货物重量校验\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#weight\").blur(function(){\r\n");
      out.write("  \t\t\tvar kg = $(\"#weight\").val();\r\n");
      out.write("  \t\t\tvar zl =  /^\\d+(\\.\\d+)?$/;\r\n");
      out.write("  \t\t\tif(zl.test(kg)){\r\n");
      out.write("  \t\t\t\t$(\"#zlSpan\").html(\"\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t}else{\r\n");
      out.write("  \t\t\t\tif(kg==''||kg==null||kg=='null'){\r\n");
      out.write("  \t\t\t\t\t$(\"#zlSpan\").html(\"亲！货物重量还没填写\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}else{\r\n");
      out.write("  \t\t\t\t\t$(\"#zlSpan\").html(\"请输入数字\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\t\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t//物品价值校验\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#money\").blur(function(){\r\n");
      out.write("  \t\t\tvar kg = $(\"#money\").val();\r\n");
      out.write("  \t\t\tvar zl =  /^\\d+(\\.\\d+)?$/;\r\n");
      out.write("  \t\t\tif(zl.test(kg)){\r\n");
      out.write("  \t\t\t\t$(\"#jzSpan\").html(\"\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t}else{\r\n");
      out.write("  \t\t\t\tif(kg==''||kg==null||kg=='null'){\r\n");
      out.write("  \t\t\t\t\t$(\"#jzSpan\").html(\"亲！物品价值还没填写\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}else{\r\n");
      out.write("  \t\t\t\t\t$(\"#jzSpan\").html(\"请输入数字\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\t\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t//报价金额校验\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#quote\").blur(function(){\r\n");
      out.write("  \t\t\tvar kg = $(\"#quote\").val();\r\n");
      out.write("  \t\t\tvar zl =  /^\\d+(\\.\\d+)?$/;\r\n");
      out.write("  \t\t\tif(zl.test(kg)){\r\n");
      out.write("  \t\t\t\t$(\"#quoteSpan\").html(\"\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t}else{\r\n");
      out.write("  \t\t\t\tif(kg==''||kg==null||kg=='null'){\r\n");
      out.write("  \t\t\t\t\t$(\"#quoteSpan\").html(\"亲！报价金额还没填写\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}else{\r\n");
      out.write("  \t\t\t\t\t$(\"#quoteSpan\").html(\"请输入数字\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\t\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t\r\n");
      out.write("  \t//发货人姓名不可为空\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#fhname\").blur(function(){\r\n");
      out.write("  \t\t\tvar phone = $(\"#fhname\").val();\r\n");
      out.write("\r\n");
      out.write("  \t\t\tvar phoneNum =  /^[\\u4E00-\\u9FA5]{2,4}$/;\r\n");
      out.write("  \t\t\tif(phoneNum.test(phone)){\r\n");
      out.write("  \t\t\t\t$(\"#nameSpan\").html(\"\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t} else {\r\n");
      out.write("  \t\t\t\tif(phone==''||phone==null||phone=='null'){\r\n");
      out.write("  \t\t\t\t\t//alert(11);\r\n");
      out.write("  \t\t\t\t\t$(\"#nameSpan\").html(\"亲！发货人姓名不可为空\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t} else {\r\n");
      out.write("\t  \t\t\t\t$(\"#nameSpan\").html(\"请填写正确的格式!!\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t//收货人姓名不可为空\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("  \t\t$(\"#shname\").blur(function(){\r\n");
      out.write("  \t\t\tvar phone = $(\"#shname\").val();\r\n");
      out.write("\r\n");
      out.write("  \t\t\tvar phoneNum =/^[\\u4E00-\\u9FA5]{2,4}$/;\r\n");
      out.write("  \t\t\tif(phoneNum.test(phone)){\r\n");
      out.write("  \t\t\t\t$(\"#shSpan\").html(\"\").css(\"color\",\"green\");\r\n");
      out.write("  \t\t\t} else {\r\n");
      out.write("  \t\t\t\tif(phone==''||phone==null||phone=='null'){\r\n");
      out.write("  \t\t\t\t\t//alert(11);\r\n");
      out.write("  \t\t\t\t\t$(\"#shSpan\").html(\"亲！收货人姓名不可为空\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t} else {\r\n");
      out.write("\t  \t\t\t\t$(\"#shSpan\").html(\"请填写正确的格式!!\").css(\"color\",\"red\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t</script>\r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"js/sanjiliandong.js\"></script>\r\n");
      out.write("  \t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "forward/top.do", out, true);
      out.write("\r\n");
      out.write("\t\t<form action=\"qtorder/add.do\" method=\"post\" onsubmit=\"return verify();\" id=\"form\">\r\n");
      out.write("\t\t<div class=\"about-us\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cebian\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"imgs/ww.png\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/images/ww.png\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>网上下单</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>ORDERED</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ab-cebian\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cebian-lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>全国服务热线 :</strong></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><span>0512-57995109</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>TEL:</strong>0512-57995109</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><strong>QQ:</strong>1927732720</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bread-xie\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forward/index.do\" tppabs=\"http://www.17sucai.com/preview/850167/2017-12-22/kunshanwuliu/index.jsp\">首页</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forward/xiadan.do\">网上下单</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"about-jianjie clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">所属门店<span >*</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fhsf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"province\" id=\"province1\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"city\" id=\"city1\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"area\" id=\"area1\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>所属门店地址<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input type=\"text\" name=\"sender_adr\" id=\"address\" value=\"\" /> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"order_now_store\" readonly=\"readonly\" id=\"address1\"  >\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\"><span ></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fhsf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>发货人姓名<span id=\"nameSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sender_name\" id=\"fhname\" value=\"\"\t />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>发货人手机号码<span id=\"phoneSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sender_phone\" id=\"phone\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6\">发货省份<span >*</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fhsf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"province\" id=\"province\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"city\" id=\"city\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"area\" id=\"area\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>发货详细地址<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input type=\"text\" name=\"sender_adr\" id=\"address\" value=\"\" /> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"sender_adr\" id=\"address\"  >\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\"><span ></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fhsf\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>收货人姓名<span id=\"shSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"accepter_name\" id=\"shname\" value=\"\" msg=\"*为必填项\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>收货人手机号<span id=\"telSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"accepter_phone\" id=\"tel\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>收货城市<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fhsf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"province\" id=\"province2\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"city\" id=\"city2\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"area\" id=\"area2\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>收货详细地址<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input type=\"text\" name=\"accepter_adr\" id=\"accepter_adr\" value=\"\" id=\"caddress1\"/> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"accepter_adr\" id=\"address2\"  >\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\"><span ></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fhsf\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>货物名称<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"goods_name\" id=\"goods_name\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>货物重量(Kg)<span id=\"zlSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"goods_weight\" id=\"weight\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>备注<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"goods_remarks\" type=\"text\" />\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>付款方式<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"cost_type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"--\" selected=\"selected\">--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"现金\">现金</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"到付\">到付</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>保价金额<span id=\"quoteSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"goods_supportvalue\" type=\"text\" id=\"quote\"/>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>下单时间<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"order_time\" readonly=\"readonly\" id=\"order_time\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>是否保价<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"goods_ifsupportvalue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\" >否</option>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\" >是</option>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>邮编号码<span id=\"codeSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"accepter_zipcode\" id=\"zidcode\" >\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>物品类型<span>*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"goods_type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"服饰\">服饰</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"视频\">视频</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"文件\">文件</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"日用品\">日用品</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"家具\">家具</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"家电\">家电</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"数码\">数码</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"食品\">食品</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"其他\">其他</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>物品价值<span id=\"jzSpan\">*</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"goods_value\" id=\"money\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><span ></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary\" value=\"提交\"  />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "forward/bottom.do", out, true);
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
