/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-05-23 07:24:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.abnormalOrder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class addBadOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
request.setAttribute("path", path);
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'addorder.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/css/bootstrap.css\" type=\"text/css\"></link>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/js/laydate/laydate.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/js/layer/layer.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \t$(document).ready(function(){\r\n");
      out.write("  \t\t $(\"#subtn\").click(function(){\r\n");
      out.write("  \t\t //保存操作\r\n");
      out.write("  \t\t\t$('#form1').form('submit',{  //给form表单绑定submit事件\r\n");
      out.write("\t\t\t\turl: \"bad/saveBadOrder.do\",//请求URL地址\r\n");
      out.write("\t\t\t\tonSubmit: function(){//对form表单校验\r\n");
      out.write("\t\t\t\t\treturn $(this).form('validate');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(result){//数据保存后的回调函数\r\n");
      out.write("\t\t\t\t\tvar result = eval('('+result+')');//eval把json字符串转换为json对象\r\n");
      out.write("\t\t\t\t\t//alert(result.errorMsg);\r\n");
      out.write("\t\t\t\t\tif (result.msg){//判断，如果错误信息不为空\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({//easyUI封装的浏览器右下角弹框\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '提示信息',//弹框标题\r\n");
      out.write("\t\t\t\t\t\t\tmsg: result.msg//提示信息\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\tif(result.msg=='提交成功') {\r\n");
      out.write("\t\t\t\t\t/* \t$('#dlg').dialog('close');\t\t// 关闭弹出框\r\n");
      out.write("\t\t\t\t\t\t$('#tt').datagrid('reload');\t// 刷新父窗口 */\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"bad/toAdd.do\";\r\n");
      out.write("\t\t\t\t\t\t//function(){window.location.href=\"bad/toAdd.do\";}\r\n");
      out.write("\t\t\t\t\t\t$('#form1').form('clear');\r\n");
      out.write("\t\t\t\t\t\t$('#badtype').val('0');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("  \t\t$(\"#haha\").click(function(){\r\n");
      out.write("  /* \t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bad_select1.action?mailnumber=\"+$(\"#mailnumber\").val(); */\r\n");
      out.write("  \t\t\t$('#form1').form('load',\"bad/allOrder.do?order_mailnum=\"+$(\"#order_mailnum\").val());\r\n");
      out.write("  \t\t\t if($('#goods_ifsupportvalue').val()=='1'){\r\n");
      out.write("  \t\t\t\t$('#goods_ifsupportvalue').val('是');\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\tif($('#goods_ifsupportvalue').val()=='2')\t{\r\n");
      out.write("  \t\t\t\t$('#goods_ifsupportvalue').val('否');\r\n");
      out.write("  \t\t\t}  \r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t});\r\n");
      out.write("  \t//action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/badorder_add.action\" method=\"post\"\r\n");
      out.write("  </script>\r\n");
      out.write("  <style>\r\n");
      out.write("  \t#add{\r\n");
      out.write("  \t\t\tbackground-color:#538EC4;\r\n");
      out.write("  \t\t\theight:65px;\r\n");
      out.write("  \t\t\tfont-size:30px;\r\n");
      out.write("  \t\t\tline-height:65px;\r\n");
      out.write("  \t\t\tcolor:white;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \ttable{\r\n");
      out.write("  \t\t\twidth:800px;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \ttable tr{\r\n");
      out.write("  \t\theight:60px;\r\n");
      out.write("  \t}\r\n");
      out.write("  \ttable tr td{\r\n");
      out.write("  \t\ttext-align:center;\r\n");
      out.write("  \t}\r\n");
      out.write("  </style>\r\n");
      out.write("  <body>\r\n");
      out.write("  <div id=\"add\">异常单信息添加</div>\r\n");
      out.write("  <div class=\"container\" style=\"margin-top:50px\" >\r\n");
      out.write("  <div class=\"row clearfix\">\r\n");
      out.write("  <div class=\"col-md-12 column\">\r\n");
      out.write("  <fieldset class=\"fi1\">\r\n");
      out.write("  <legend>添加新的异常单信息</legend>\r\n");
      out.write("    <form role=\"form\" id=\"form1\" method=\"post\">\r\n");
      out.write("    \t<table border=\"0\">\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td>邮寄单号</td>\r\n");
      out.write("    \t\t\t<td><input class=\"form-control\" type=\"text\" name=\"order_mailnum\" id=\"order_mailnum\" /></td>\r\n");
      out.write("    \t\t\t<td><input class=\"btn btn-success\" type=\"button\" value=\"查询\"  id=\"haha\"/></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td>客户姓名</td>\r\n");
      out.write("    \t\t\t<td><input class=\"form-control\" type=\"text\"  name=\"sender_name\"/></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td>货物总值</td>\r\n");
      out.write("    \t\t\t<td><input class=\"form-control\" type=\"text\"  name=\"goods_value\"/></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td>是否保价</td>\r\n");
      out.write("    \t\t\t<td>\r\n");
      out.write("    \t\t\t<input class=\"form-control\" type=\"text\" name=\"goods_ifsupportvalue\"  id=\"goods_ifsupportvalue\"  \r\n");
      out.write("    \t\t\t/>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td>保价金额</td>\r\n");
      out.write("    \t\t\t<td><input class=\"form-control\" type=\"text\" name=\"goods_supportvalue\"  id=\"goods_supportvalue\" /></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td>异常类型</td>\r\n");
      out.write("    \t\t\t<td><select class=\"form-control\" name=\"badtype\" id=\"badtype\">\r\n");
      out.write("    \t\t\t\t<option value=\"0\">货品破损</option>\r\n");
      out.write("    \t\t\t\t<option value=\"1\">货品丢失</option>\r\n");
      out.write("    \t\t\t\t<option value=\"2\">延期到达</option>\r\n");
      out.write("    \t\t\t\t<option value=\"3\">其他</option>\r\n");
      out.write("    \t\t\t</select></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td>赔付金额</td>\r\n");
      out.write("    \t\t\t<td><input type=\"text\" class=\"form-control\" name=\"badpay\" onkeyup=\"this.value=this.value.replace(/\\D/gi,'')\"/></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr >\r\n");
      out.write("    \t\t\t<td valign=\"top\">异常信息</td>\r\n");
      out.write("    \t\t\t<td>\r\n");
      out.write("    \t\t\t<textarea class=\"form-control\" rows=\"3\" cols=\"50\" name=\"badreason\"></textarea>\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"order_time\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"sender_phone\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"sender_adr\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"accepter_name\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"accepter_phone\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"accepter_adr\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"goods_type\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"goods_cost\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"cost_type\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t<input class=\"form-control\" name=\"id\" type=\"hidden\" >\r\n");
      out.write("    \t\t\t</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<td colspan=\"2\"><input class=\"btn btn-success\"  type=\"button\" value=\"提交\" id=\"subtn\" style=\"width:150px;height:40px\" /></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</table>\r\n");
      out.write("    </form>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
